spring:
  # Redis 集群配置
  redis:
    cluster:
      max-redirects: 3
      nodes:
        - 10.12.12.222:6481
        - 10.12.12.223:6482
        - 10.12.8.196:6483
        - 10.12.12.222:6484
        - 10.12.12.223:6485
        - 10.12.8.196:6486
    #    password:
    timeout: 6000
    lettuce:
      pool:
        max-active: 50      # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5         # 连接池中的最大空闲连接
        min-idle: 0         #  连接池中的最小空闲连接
    database: 0


